// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_info_base.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_user_5finfo_5fbase_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_user_5finfo_5fbase_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_user_5finfo_5fbase_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_user_5finfo_5fbase_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_user_5finfo_5fbase_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_user_5finfo_5fbase_2eproto_metadata_getter(int index);
namespace ssp {
class UserInfoBase;
struct UserInfoBaseDefaultTypeInternal;
extern UserInfoBaseDefaultTypeInternal _UserInfoBase_default_instance_;
}  // namespace ssp
PROTOBUF_NAMESPACE_OPEN
template<> ::ssp::UserInfoBase* Arena::CreateMaybeMessage<::ssp::UserInfoBase>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ssp {

// ===================================================================

class UserInfoBase PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ssp.UserInfoBase) */ {
 public:
  inline UserInfoBase() : UserInfoBase(nullptr) {}
  virtual ~UserInfoBase();
  explicit constexpr UserInfoBase(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UserInfoBase(const UserInfoBase& from);
  UserInfoBase(UserInfoBase&& from) noexcept
    : UserInfoBase() {
    *this = ::std::move(from);
  }

  inline UserInfoBase& operator=(const UserInfoBase& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserInfoBase& operator=(UserInfoBase&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const UserInfoBase& default_instance() {
    return *internal_default_instance();
  }
  static inline const UserInfoBase* internal_default_instance() {
    return reinterpret_cast<const UserInfoBase*>(
               &_UserInfoBase_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UserInfoBase& a, UserInfoBase& b) {
    a.Swap(&b);
  }
  inline void Swap(UserInfoBase* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserInfoBase* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline UserInfoBase* New() const final {
    return CreateMaybeMessage<UserInfoBase>(nullptr);
  }

  UserInfoBase* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<UserInfoBase>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const UserInfoBase& from);
  void MergeFrom(const UserInfoBase& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserInfoBase* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ssp.UserInfoBase";
  }
  protected:
  explicit UserInfoBase(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_user_5finfo_5fbase_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserNameFieldNumber = 3,
    kNickNameFieldNumber = 4,
    kPasswordFieldNumber = 10,
    kVerFieldNumber = 1,
    kUserIdFieldNumber = 2,
    kRegTimeFieldNumber = 5,
    kFromFieldNumber = 6,
    kLoginTimeFieldNumber = 7,
    kLastLoginTimeFieldNumber = 8,
    kFreshTimeFieldNumber = 9,
    kLogoutTimeFieldNumber = 11,
    kDbFlagFieldNumber = 12,
  };
  // optional string user_name = 3;
  bool has_user_name() const;
  private:
  bool _internal_has_user_name() const;
  public:
  void clear_user_name();
  const std::string& user_name() const;
  void set_user_name(const std::string& value);
  void set_user_name(std::string&& value);
  void set_user_name(const char* value);
  void set_user_name(const char* value, size_t size);
  std::string* mutable_user_name();
  std::string* release_user_name();
  void set_allocated_user_name(std::string* user_name);
  private:
  const std::string& _internal_user_name() const;
  void _internal_set_user_name(const std::string& value);
  std::string* _internal_mutable_user_name();
  public:

  // optional string nick_name = 4;
  bool has_nick_name() const;
  private:
  bool _internal_has_nick_name() const;
  public:
  void clear_nick_name();
  const std::string& nick_name() const;
  void set_nick_name(const std::string& value);
  void set_nick_name(std::string&& value);
  void set_nick_name(const char* value);
  void set_nick_name(const char* value, size_t size);
  std::string* mutable_nick_name();
  std::string* release_nick_name();
  void set_allocated_nick_name(std::string* nick_name);
  private:
  const std::string& _internal_nick_name() const;
  void _internal_set_nick_name(const std::string& value);
  std::string* _internal_mutable_nick_name();
  public:

  // optional string password = 10;
  bool has_password() const;
  private:
  bool _internal_has_password() const;
  public:
  void clear_password();
  const std::string& password() const;
  void set_password(const std::string& value);
  void set_password(std::string&& value);
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  std::string* mutable_password();
  std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // optional uint32 ver = 1;
  bool has_ver() const;
  private:
  bool _internal_has_ver() const;
  public:
  void clear_ver();
  ::PROTOBUF_NAMESPACE_ID::uint32 ver() const;
  void set_ver(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ver() const;
  void _internal_set_ver(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 user_id = 2;
  bool has_user_id() const;
  private:
  bool _internal_has_user_id() const;
  public:
  void clear_user_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 user_id() const;
  void set_user_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_user_id() const;
  void _internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 reg_time = 5;
  bool has_reg_time() const;
  private:
  bool _internal_has_reg_time() const;
  public:
  void clear_reg_time();
  ::PROTOBUF_NAMESPACE_ID::uint32 reg_time() const;
  void set_reg_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_reg_time() const;
  void _internal_set_reg_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 from = 6;
  bool has_from() const;
  private:
  bool _internal_has_from() const;
  public:
  void clear_from();
  ::PROTOBUF_NAMESPACE_ID::uint32 from() const;
  void set_from(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_from() const;
  void _internal_set_from(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 login_time = 7;
  bool has_login_time() const;
  private:
  bool _internal_has_login_time() const;
  public:
  void clear_login_time();
  ::PROTOBUF_NAMESPACE_ID::uint32 login_time() const;
  void set_login_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_login_time() const;
  void _internal_set_login_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 last_login_time = 8;
  bool has_last_login_time() const;
  private:
  bool _internal_has_last_login_time() const;
  public:
  void clear_last_login_time();
  ::PROTOBUF_NAMESPACE_ID::uint32 last_login_time() const;
  void set_last_login_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_last_login_time() const;
  void _internal_set_last_login_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 fresh_time = 9;
  bool has_fresh_time() const;
  private:
  bool _internal_has_fresh_time() const;
  public:
  void clear_fresh_time();
  ::PROTOBUF_NAMESPACE_ID::uint32 fresh_time() const;
  void set_fresh_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_fresh_time() const;
  void _internal_set_fresh_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 logout_time = 11;
  bool has_logout_time() const;
  private:
  bool _internal_has_logout_time() const;
  public:
  void clear_logout_time();
  ::PROTOBUF_NAMESPACE_ID::uint32 logout_time() const;
  void set_logout_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_logout_time() const;
  void _internal_set_logout_time(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 db_flag = 12;
  bool has_db_flag() const;
  private:
  bool _internal_has_db_flag() const;
  public:
  void clear_db_flag();
  ::PROTOBUF_NAMESPACE_ID::uint32 db_flag() const;
  void set_db_flag(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_db_flag() const;
  void _internal_set_db_flag(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:ssp.UserInfoBase)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nick_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ver_;
  ::PROTOBUF_NAMESPACE_ID::uint32 user_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 reg_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 from_;
  ::PROTOBUF_NAMESPACE_ID::uint32 login_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 last_login_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 fresh_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 logout_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 db_flag_;
  friend struct ::TableStruct_user_5finfo_5fbase_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UserInfoBase

// optional uint32 ver = 1;
inline bool UserInfoBase::_internal_has_ver() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool UserInfoBase::has_ver() const {
  return _internal_has_ver();
}
inline void UserInfoBase::clear_ver() {
  ver_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::_internal_ver() const {
  return ver_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::ver() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.ver)
  return _internal_ver();
}
inline void UserInfoBase::_internal_set_ver(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  ver_ = value;
}
inline void UserInfoBase::set_ver(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ver(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.ver)
}

// optional uint32 user_id = 2;
inline bool UserInfoBase::_internal_has_user_id() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool UserInfoBase::has_user_id() const {
  return _internal_has_user_id();
}
inline void UserInfoBase::clear_user_id() {
  user_id_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::_internal_user_id() const {
  return user_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::user_id() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.user_id)
  return _internal_user_id();
}
inline void UserInfoBase::_internal_set_user_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  user_id_ = value;
}
inline void UserInfoBase::set_user_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.user_id)
}

// optional string user_name = 3;
inline bool UserInfoBase::_internal_has_user_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool UserInfoBase::has_user_name() const {
  return _internal_has_user_name();
}
inline void UserInfoBase::clear_user_name() {
  user_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& UserInfoBase::user_name() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.user_name)
  return _internal_user_name();
}
inline void UserInfoBase::set_user_name(const std::string& value) {
  _internal_set_user_name(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.user_name)
}
inline std::string* UserInfoBase::mutable_user_name() {
  // @@protoc_insertion_point(field_mutable:ssp.UserInfoBase.user_name)
  return _internal_mutable_user_name();
}
inline const std::string& UserInfoBase::_internal_user_name() const {
  return user_name_.Get();
}
inline void UserInfoBase::_internal_set_user_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  user_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void UserInfoBase::set_user_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  user_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ssp.UserInfoBase.user_name)
}
inline void UserInfoBase::set_user_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  user_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:ssp.UserInfoBase.user_name)
}
inline void UserInfoBase::set_user_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  user_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ssp.UserInfoBase.user_name)
}
inline std::string* UserInfoBase::_internal_mutable_user_name() {
  _has_bits_[0] |= 0x00000001u;
  return user_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* UserInfoBase::release_user_name() {
  // @@protoc_insertion_point(field_release:ssp.UserInfoBase.user_name)
  if (!_internal_has_user_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return user_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UserInfoBase::set_allocated_user_name(std::string* user_name) {
  if (user_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  user_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ssp.UserInfoBase.user_name)
}

// optional string nick_name = 4;
inline bool UserInfoBase::_internal_has_nick_name() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool UserInfoBase::has_nick_name() const {
  return _internal_has_nick_name();
}
inline void UserInfoBase::clear_nick_name() {
  nick_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& UserInfoBase::nick_name() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.nick_name)
  return _internal_nick_name();
}
inline void UserInfoBase::set_nick_name(const std::string& value) {
  _internal_set_nick_name(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.nick_name)
}
inline std::string* UserInfoBase::mutable_nick_name() {
  // @@protoc_insertion_point(field_mutable:ssp.UserInfoBase.nick_name)
  return _internal_mutable_nick_name();
}
inline const std::string& UserInfoBase::_internal_nick_name() const {
  return nick_name_.Get();
}
inline void UserInfoBase::_internal_set_nick_name(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  nick_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void UserInfoBase::set_nick_name(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  nick_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ssp.UserInfoBase.nick_name)
}
inline void UserInfoBase::set_nick_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  nick_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:ssp.UserInfoBase.nick_name)
}
inline void UserInfoBase::set_nick_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  nick_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ssp.UserInfoBase.nick_name)
}
inline std::string* UserInfoBase::_internal_mutable_nick_name() {
  _has_bits_[0] |= 0x00000002u;
  return nick_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* UserInfoBase::release_nick_name() {
  // @@protoc_insertion_point(field_release:ssp.UserInfoBase.nick_name)
  if (!_internal_has_nick_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return nick_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UserInfoBase::set_allocated_nick_name(std::string* nick_name) {
  if (nick_name != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  nick_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), nick_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ssp.UserInfoBase.nick_name)
}

// optional uint32 reg_time = 5;
inline bool UserInfoBase::_internal_has_reg_time() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool UserInfoBase::has_reg_time() const {
  return _internal_has_reg_time();
}
inline void UserInfoBase::clear_reg_time() {
  reg_time_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::_internal_reg_time() const {
  return reg_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::reg_time() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.reg_time)
  return _internal_reg_time();
}
inline void UserInfoBase::_internal_set_reg_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  reg_time_ = value;
}
inline void UserInfoBase::set_reg_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_reg_time(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.reg_time)
}

// optional uint32 from = 6;
inline bool UserInfoBase::_internal_has_from() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool UserInfoBase::has_from() const {
  return _internal_has_from();
}
inline void UserInfoBase::clear_from() {
  from_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::_internal_from() const {
  return from_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::from() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.from)
  return _internal_from();
}
inline void UserInfoBase::_internal_set_from(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000040u;
  from_ = value;
}
inline void UserInfoBase::set_from(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_from(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.from)
}

// optional uint32 login_time = 7;
inline bool UserInfoBase::_internal_has_login_time() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool UserInfoBase::has_login_time() const {
  return _internal_has_login_time();
}
inline void UserInfoBase::clear_login_time() {
  login_time_ = 0u;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::_internal_login_time() const {
  return login_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::login_time() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.login_time)
  return _internal_login_time();
}
inline void UserInfoBase::_internal_set_login_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000080u;
  login_time_ = value;
}
inline void UserInfoBase::set_login_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_login_time(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.login_time)
}

// optional uint32 last_login_time = 8;
inline bool UserInfoBase::_internal_has_last_login_time() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool UserInfoBase::has_last_login_time() const {
  return _internal_has_last_login_time();
}
inline void UserInfoBase::clear_last_login_time() {
  last_login_time_ = 0u;
  _has_bits_[0] &= ~0x00000100u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::_internal_last_login_time() const {
  return last_login_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::last_login_time() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.last_login_time)
  return _internal_last_login_time();
}
inline void UserInfoBase::_internal_set_last_login_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000100u;
  last_login_time_ = value;
}
inline void UserInfoBase::set_last_login_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_last_login_time(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.last_login_time)
}

// optional uint32 fresh_time = 9;
inline bool UserInfoBase::_internal_has_fresh_time() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool UserInfoBase::has_fresh_time() const {
  return _internal_has_fresh_time();
}
inline void UserInfoBase::clear_fresh_time() {
  fresh_time_ = 0u;
  _has_bits_[0] &= ~0x00000200u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::_internal_fresh_time() const {
  return fresh_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::fresh_time() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.fresh_time)
  return _internal_fresh_time();
}
inline void UserInfoBase::_internal_set_fresh_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000200u;
  fresh_time_ = value;
}
inline void UserInfoBase::set_fresh_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_fresh_time(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.fresh_time)
}

// optional string password = 10;
inline bool UserInfoBase::_internal_has_password() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool UserInfoBase::has_password() const {
  return _internal_has_password();
}
inline void UserInfoBase::clear_password() {
  password_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& UserInfoBase::password() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.password)
  return _internal_password();
}
inline void UserInfoBase::set_password(const std::string& value) {
  _internal_set_password(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.password)
}
inline std::string* UserInfoBase::mutable_password() {
  // @@protoc_insertion_point(field_mutable:ssp.UserInfoBase.password)
  return _internal_mutable_password();
}
inline const std::string& UserInfoBase::_internal_password() const {
  return password_.Get();
}
inline void UserInfoBase::_internal_set_password(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void UserInfoBase::set_password(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  password_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:ssp.UserInfoBase.password)
}
inline void UserInfoBase::set_password(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:ssp.UserInfoBase.password)
}
inline void UserInfoBase::set_password(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000004u;
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:ssp.UserInfoBase.password)
}
inline std::string* UserInfoBase::_internal_mutable_password() {
  _has_bits_[0] |= 0x00000004u;
  return password_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* UserInfoBase::release_password() {
  // @@protoc_insertion_point(field_release:ssp.UserInfoBase.password)
  if (!_internal_has_password()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return password_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void UserInfoBase::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:ssp.UserInfoBase.password)
}

// optional uint32 logout_time = 11;
inline bool UserInfoBase::_internal_has_logout_time() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool UserInfoBase::has_logout_time() const {
  return _internal_has_logout_time();
}
inline void UserInfoBase::clear_logout_time() {
  logout_time_ = 0u;
  _has_bits_[0] &= ~0x00000400u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::_internal_logout_time() const {
  return logout_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::logout_time() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.logout_time)
  return _internal_logout_time();
}
inline void UserInfoBase::_internal_set_logout_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000400u;
  logout_time_ = value;
}
inline void UserInfoBase::set_logout_time(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_logout_time(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.logout_time)
}

// optional uint32 db_flag = 12;
inline bool UserInfoBase::_internal_has_db_flag() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool UserInfoBase::has_db_flag() const {
  return _internal_has_db_flag();
}
inline void UserInfoBase::clear_db_flag() {
  db_flag_ = 0u;
  _has_bits_[0] &= ~0x00000800u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::_internal_db_flag() const {
  return db_flag_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 UserInfoBase::db_flag() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.db_flag)
  return _internal_db_flag();
}
inline void UserInfoBase::_internal_set_db_flag(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000800u;
  db_flag_ = value;
}
inline void UserInfoBase::set_db_flag(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_db_flag(value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.db_flag)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ssp

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_user_5finfo_5fbase_2eproto
